spring:
  application:
    name: matrix
    description: Matrix AI Agent Backend
    version: 1.0.0

  datasource:
    url: jdbc:postgresql://100.124.129.13:5432/matrix_db
    username: appuser
    password: strongpassword
    driver-class-name: org.postgresql.Driver

  hikari:
    minimum-idle: 5
    maximum-pool-size: 10
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 20000

#
#  sql:
#    init:
#      mode: always

  jpa:
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: qwen/qwen3-235b-a22b-thinking-2507
          temperature: 0.0

minio:
  endpoint: http://100.124.129.13:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket: matrix

jwt:
  secret: r8vKz4XqT9mL2pQ7sW3eY6uI1oP5aD9fG7hJ2kL8zXcV4bNmQ1tR6yU3wE0iO9p
  expiration: 86400

logging:
  level:
    org.springframework.ai: DEBUG
